//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.DataContracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeotaggedAssetDataContract", Namespace="http://schemas.datacontract.org/2004/07/WebServices.DataContracts")]
    public partial class GeotaggedAssetDataContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal dLatitudeField;
        
        private decimal dLongitudeField;
        
        private long lTimeStampField;
        
        private string oAssetKeyField;
        
        private string oUserIdentificationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal dLatitude
        {
            get
            {
                return this.dLatitudeField;
            }
            set
            {
                this.dLatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal dLongitude
        {
            get
            {
                return this.dLongitudeField;
            }
            set
            {
                this.dLongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lTimeStamp
        {
            get
            {
                return this.lTimeStampField;
            }
            set
            {
                this.lTimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oAssetKey
        {
            get
            {
                return this.oAssetKeyField;
            }
            set
            {
                this.oAssetKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oUserIdentification
        {
            get
            {
                return this.oUserIdentificationField;
            }
            set
            {
                this.oUserIdentificationField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDeliveryService")]
public interface IDeliveryService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/GeoTagDelivery", ReplyAction="http://tempuri.org/IDeliveryService/GeoTagDeliveryResponse")]
    void GeoTagDelivery(WebServices.DataContracts.GeotaggedAssetDataContract oGeotaggedAssetContract);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/UnTagDelivery", ReplyAction="http://tempuri.org/IDeliveryService/UnTagDeliveryResponse")]
    void UnTagDelivery(string strAssetKey);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDeliveryServiceChannel : IDeliveryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DeliveryServiceClient : System.ServiceModel.ClientBase<IDeliveryService>, IDeliveryService
{
    
    public DeliveryServiceClient()
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeliveryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void GeoTagDelivery(WebServices.DataContracts.GeotaggedAssetDataContract oGeotaggedAssetContract)
    {
        base.Channel.GeoTagDelivery(oGeotaggedAssetContract);
    }
    
    public void UnTagDelivery(string strAssetKey)
    {
        base.Channel.UnTagDelivery(strAssetKey);
    }
}
