//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.DataContracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeospatialInformationDataContract", Namespace="http://schemas.datacontract.org/2004/07/WebServices.DataContracts")]
    public partial class GeospatialInformationDataContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal dLatitudeField;
        
        private decimal dLongitudeField;
        
        private decimal dSpeedField;
        
        private int iOrientationField;
        
        private int iSessionIDField;
        
        private long lTimeStampField;
        
        private string oUserIdentificationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal dLatitude
        {
            get
            {
                return this.dLatitudeField;
            }
            set
            {
                this.dLatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal dLongitude
        {
            get
            {
                return this.dLongitudeField;
            }
            set
            {
                this.dLongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal dSpeed
        {
            get
            {
                return this.dSpeedField;
            }
            set
            {
                this.dSpeedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iOrientation
        {
            get
            {
                return this.iOrientationField;
            }
            set
            {
                this.iOrientationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iSessionID
        {
            get
            {
                return this.iSessionIDField;
            }
            set
            {
                this.iSessionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lTimeStamp
        {
            get
            {
                return this.lTimeStampField;
            }
            set
            {
                this.lTimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oUserIdentification
        {
            get
            {
                return this.oUserIdentificationField;
            }
            set
            {
                this.oUserIdentificationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeospatialInformationSetDataContract", Namespace="http://schemas.datacontract.org/2004/07/WebServices.DataContracts")]
    public partial class GeospatialInformationSetDataContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebServices.DataContracts.GeospatialInformationDataContract[] BufferedDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServices.DataContracts.GeospatialInformationDataContract[] BufferedData
        {
            get
            {
                return this.BufferedDataField;
            }
            set
            {
                this.BufferedDataField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILocationService")]
public interface ILocationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/PostGeospatialData", ReplyAction="http://tempuri.org/ILocationService/PostGeospatialDataResponse")]
    void PostGeospatialData(WebServices.DataContracts.GeospatialInformationDataContract oGeoInformationContract);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/PostBufferedGeospatialDataSet", ReplyAction="http://tempuri.org/ILocationService/PostBufferedGeospatialDataSetResponse")]
    void PostBufferedGeospatialDataSet(WebServices.DataContracts.GeospatialInformationSetDataContract oGeoInformationSetContract);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/PostBufferedHistoricalData", ReplyAction="http://tempuri.org/ILocationService/PostBufferedHistoricalDataResponse")]
    void PostBufferedHistoricalData(WebServices.DataContracts.GeospatialInformationSetDataContract oGeoInformationSetContract);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILocationServiceChannel : ILocationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LocationServiceClient : System.ServiceModel.ClientBase<ILocationService>, ILocationService
{
    
    public LocationServiceClient()
    {
    }
    
    public LocationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void PostGeospatialData(WebServices.DataContracts.GeospatialInformationDataContract oGeoInformationContract)
    {
        base.Channel.PostGeospatialData(oGeoInformationContract);
    }
    
    public void PostBufferedGeospatialDataSet(WebServices.DataContracts.GeospatialInformationSetDataContract oGeoInformationSetContract)
    {
        base.Channel.PostBufferedGeospatialDataSet(oGeoInformationSetContract);
    }
    
    public void PostBufferedHistoricalData(WebServices.DataContracts.GeospatialInformationSetDataContract oGeoInformationSetContract)
    {
        base.Channel.PostBufferedHistoricalData(oGeoInformationSetContract);
    }
}
