//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="INotifierService")]
public interface INotifierService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifierService/GISNotify", ReplyAction="http://tempuri.org/INotifierService/GISNotifyResponse")]
    void GISNotify(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifierService/GISNotify", ReplyAction="http://tempuri.org/INotifierService/GISNotifyResponse")]
    System.Threading.Tasks.Task GISNotifyAsync(string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INotifierServiceChannel : INotifierService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NotifierServiceClient : System.ServiceModel.ClientBase<INotifierService>, INotifierService
{
    
    public NotifierServiceClient()
    {
    }
    
    public NotifierServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NotifierServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotifierServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotifierServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void GISNotify(string message)
    {
        base.Channel.GISNotify(message);
    }
    
    public System.Threading.Tasks.Task GISNotifyAsync(string message)
    {
        return base.Channel.GISNotifyAsync(message);
    }
}
