//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDeliveryService")]
public interface IDeliveryService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/SubmitGeoTaggedDelivery", ReplyAction="http://tempuri.org/IDeliveryService/SubmitGeoTaggedDeliveryResponse")]
    void SubmitGeoTaggedDelivery(string strGeoTaggedDeliveryObject);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/SubmitGeoTaggedDelivery", ReplyAction="http://tempuri.org/IDeliveryService/SubmitGeoTaggedDeliveryResponse")]
    System.Threading.Tasks.Task SubmitGeoTaggedDeliveryAsync(string strGeoTaggedDeliveryObject);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/GetDeliveryInformation", ReplyAction="http://tempuri.org/IDeliveryService/GetDeliveryInformationResponse")]
    string GetDeliveryInformation(string strItemID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/GetDeliveryInformation", ReplyAction="http://tempuri.org/IDeliveryService/GetDeliveryInformationResponse")]
    System.Threading.Tasks.Task<string> GetDeliveryInformationAsync(string strItemID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDeliveryServiceChannel : IDeliveryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DeliveryServiceClient : System.ServiceModel.ClientBase<IDeliveryService>, IDeliveryService
{
    
    public DeliveryServiceClient()
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeliveryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SubmitGeoTaggedDelivery(string strGeoTaggedDeliveryObject)
    {
        base.Channel.SubmitGeoTaggedDelivery(strGeoTaggedDeliveryObject);
    }
    
    public System.Threading.Tasks.Task SubmitGeoTaggedDeliveryAsync(string strGeoTaggedDeliveryObject)
    {
        return base.Channel.SubmitGeoTaggedDeliveryAsync(strGeoTaggedDeliveryObject);
    }
    
    public string GetDeliveryInformation(string strItemID)
    {
        return base.Channel.GetDeliveryInformation(strItemID);
    }
    
    public System.Threading.Tasks.Task<string> GetDeliveryInformationAsync(string strItemID)
    {
        return base.Channel.GetDeliveryInformationAsync(strItemID);
    }
}
