//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDeliveryService")]
public interface IDeliveryService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/GeoTagDelivery", ReplyAction="http://tempuri.org/IDeliveryService/GeoTagDeliveryResponse")]
    void GeoTagDelivery(string strGeoTaggedDeliveryObject);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/GeoTagDelivery", ReplyAction="http://tempuri.org/IDeliveryService/GeoTagDeliveryResponse")]
    System.Threading.Tasks.Task GeoTagDeliveryAsync(string strGeoTaggedDeliveryObject);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/UnTagDelivery", ReplyAction="http://tempuri.org/IDeliveryService/UnTagDeliveryResponse")]
    void UnTagDelivery(string strAssetKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/UnTagDelivery", ReplyAction="http://tempuri.org/IDeliveryService/UnTagDeliveryResponse")]
    System.Threading.Tasks.Task UnTagDeliveryAsync(string strAssetKey);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDeliveryServiceChannel : IDeliveryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DeliveryServiceClient : System.ServiceModel.ClientBase<IDeliveryService>, IDeliveryService
{
    
    public DeliveryServiceClient()
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeliveryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeliveryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void GeoTagDelivery(string strGeoTaggedDeliveryObject)
    {
        base.Channel.GeoTagDelivery(strGeoTaggedDeliveryObject);
    }
    
    public System.Threading.Tasks.Task GeoTagDeliveryAsync(string strGeoTaggedDeliveryObject)
    {
        return base.Channel.GeoTagDeliveryAsync(strGeoTaggedDeliveryObject);
    }
    
    public void UnTagDelivery(string strAssetKey)
    {
        base.Channel.UnTagDelivery(strAssetKey);
    }
    
    public System.Threading.Tasks.Task UnTagDeliveryAsync(string strAssetKey)
    {
        return base.Channel.UnTagDeliveryAsync(strAssetKey);
    }
}
