//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILocationService")]
public interface ILocationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/PostGeospatialData", ReplyAction="http://tempuri.org/ILocationService/PostGeospatialDataResponse")]
    void PostGeospatialData(string strGeospatialDataJsonString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/PostGeospatialData", ReplyAction="http://tempuri.org/ILocationService/PostGeospatialDataResponse")]
    System.Threading.Tasks.Task PostGeospatialDataAsync(string strGeospatialDataJsonString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/PostBufferedGeospatialDataSet", ReplyAction="http://tempuri.org/ILocationService/PostBufferedGeospatialDataSetResponse")]
    void PostBufferedGeospatialDataSet(string strBufferedGeospatialDataSetJsonString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/PostBufferedGeospatialDataSet", ReplyAction="http://tempuri.org/ILocationService/PostBufferedGeospatialDataSetResponse")]
    System.Threading.Tasks.Task PostBufferedGeospatialDataSetAsync(string strBufferedGeospatialDataSetJsonString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILocationServiceChannel : ILocationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LocationServiceClient : System.ServiceModel.ClientBase<ILocationService>, ILocationService
{
    
    public LocationServiceClient()
    {
    }
    
    public LocationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void PostGeospatialData(string strGeospatialDataJsonString)
    {
        base.Channel.PostGeospatialData(strGeospatialDataJsonString);
    }
    
    public System.Threading.Tasks.Task PostGeospatialDataAsync(string strGeospatialDataJsonString)
    {
        return base.Channel.PostGeospatialDataAsync(strGeospatialDataJsonString);
    }
    
    public void PostBufferedGeospatialDataSet(string strBufferedGeospatialDataSetJsonString)
    {
        base.Channel.PostBufferedGeospatialDataSet(strBufferedGeospatialDataSetJsonString);
    }
    
    public System.Threading.Tasks.Task PostBufferedGeospatialDataSetAsync(string strBufferedGeospatialDataSetJsonString)
    {
        return base.Channel.PostBufferedGeospatialDataSetAsync(strBufferedGeospatialDataSetJsonString);
    }
}
